// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using RideMate.Infrastructure.Data;

#nullable disable

namespace RideMate.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519000000_LocationPresenceDetails")]
    partial class LocationPresenceDetails
    {
    }
}
